#!/bin/bash
# 调试桌面端文件接收问题

echo "=== 桌面端文件接收调试指南 ==="
echo ""
echo "问题：桌面端后台显示 '[Web Server] 已发送文件接收 Tauri 事件'，但前端没有显示"
echo ""
echo "步骤 1: 重新编译桌面端（包含新的调试日志）"
echo "----------------------------------------"
echo "cd src-tauri && cargo build --bin lanchat --features desktop"
echo ""
echo "步骤 2: 启动桌面端"
echo "----------------------------------------"
echo "./src-tauri/target/debug/lanchat"
echo ""
echo "步骤 3: 打开浏览器开发者工具"
echo "----------------------------------------"
echo "按 F12 打开控制台"
echo ""
echo "步骤 4: 点击用户列表中的发送者"
echo "----------------------------------------"
echo "⚠️ 重要：必须先点击用户列表中的用户，打开聊天窗口！"
echo "这会设置 window.currentChatPeer"
echo ""
echo "步骤 5: 让对方发送文件"
echo "----------------------------------------"
echo ""
echo "步骤 6: 检查控制台日志"
echo "----------------------------------------"
echo "应该看到以下日志："
echo ""
echo "  [JS-App] 收到新消息事件"
echo "  [JS-App] 事件内容: {"
echo "    \"from_id\": \"发送者的UUID\","
echo "    \"msg_type\": \"file\","
echo "    \"file_name\": \"文件名\","
echo "    ..."
echo "  }"
echo "  [UI] 收到新消息: ..."
echo "  [UI] 当前聊天对象: { id: \"...\", name: \"...\", addr: \"...\" }"
echo "  [UI] 匹配当前聊天对象，显示消息  <-- 关键！"
echo "  [UI] addMessageToChat 被调用"
echo "  [UI] 消息类型: file"
echo "  [UI] 渲染文件消息: 文件名"
echo "  [UI] 消息已添加到聊天窗口"
echo ""
echo "如果看到 '[UI] 不匹配当前聊天对象，消息未显示'："
echo "----------------------------------------"
echo "说明："
echo "1. 没有打开聊天窗口（window.currentChatPeer 为空）"
echo "2. 或者打开的聊天窗口不是发送者的（ID 不匹配）"
echo ""
echo "解决方法："
echo "- 确保点击了用户列表中的发送者"
echo "- 检查发送者的 ID 是否正确"
echo ""
echo "在控制台执行以下命令检查："
echo "  console.log('当前聊天对象:', window.currentChatPeer);"
echo ""
